# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dockertrigger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://dockertrigger.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a05e7d043cca4ca78f4835c1cb1825be }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b57e5b28d54149adb537efe707a500b4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: dockertrigger.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a05e7d043cca4ca78f4835c1cb1825be }}/dockertrigger:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dockertrigger'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_39e9aa0911a645bda8eb4490eb73fe2a }}
        images: 'dockertrigger.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a05e7d043cca4ca78f4835c1cb1825be }}/dockertrigger:${{ github.sha }}'